### ISSUE TITLE
Small difference between CSV and JSON

### ISSUE THREAD

**Issue by zmoon** [adactio/TheSession-data#16]
In tunes,
```
                        username_json                  username_csv
  17736  Seamus "Piobaire" MacOibicin  Seamus Piobaire" MacOibicin"
```
This is tune ID 228, setting ID 27044.

Similar issue to #15 I suppose, i.e. quotes in the field.

**Comment by adactio** [comment]
This should be all fixed now.

**Comment by zmoon** [comment]
@adactio , at least from the perspective of pandas, `"Seamus "Piobaire" MacOibicin"` in the CSV is still an issue.

The C parser (default) still gives `Seamus Piobaire" MacOibicin"` as above, and the Python parser chokes with `ParserError: ',' expected after '"'`.

Having experimented a little, I can say it will get read in correctly if, e.g.
* -> `"Seamus ""Piobaire"" MacOibicin"` (default "doublequote" settings)
* -> `"Seamus \"Piobaire\" MacOibicin"` (if use `quotechar="\\"`)

**Comment by adactio** [comment]
Whoops! Forgot to re-export the fixed data dump—all done now!

**Comment by zmoon** [comment]
Ahh gotcha. Thanks a lot!
